import { useEffect, useRef, useState, type FormEvent } from 'react';
import { Home, Compass, Clapperboard, FolderOpen, Layers3, Play, Plus, ArrowUpRight, ArrowRight, Search, Sparkles, BriefcaseBusiness, PanelLeftClose, Menu, X, RotateCcw, RefreshCw, CircleHelp, Film, Clock3, ShieldCheck, LockKeyhole, Download, Users, Info, FileText } from 'lucide-react';
import { Animatic, Artwork, Button, Dialog, Empty, Field, IconButton, NoticeContext, PageHead, SectionHead, Status, Tag, formatDate, nav, useDemo, useNotice, useRoute } from './ui';
import { createAssistantProject, getSaveError, isClosed, joinTask, resetDemo, setRole, update } from './service';
import type { Asset, Commission, IP, Project } from './types';
import DirectorStudio from './Studio';
import WriterStudio from './WriterStudio';
import CanvasDemo from './CanvasDemo';
import { assistantPath, resolveWorkspace } from './workspace-route';
import { scriptCurrent, assetsCurrent, storyboardCurrent, promptsCurrent } from './assistant-model';
import Owner from './Owner';

const links = [{ path: '/', label: '首页', icon: Home }, { path: '/ips', label: 'IP 广场', icon: Compass }, { path: '/tasks', label: '任务广场', icon: Clapperboard }, { path: '/projects', label: '我的项目', icon: FolderOpen }, { path: '/canvas', label: '画布创作', icon: Layers3 }, { path: '/assets', label: '资产库', icon: Layers3 }, { path: '/works', label: '作品展映', icon: Play }];
const projectLinks = [{ path: '/assistants/writer', label: '编剧助手', icon: FileText }, { path: '/assistants/director', label: '导演助手', icon: Film }];
export default function App() {
  const state = useDemo(), route = useRoute(); const [sidebar, setSidebar] = useState(false), [toast, setToast] = useState(''), [reset, setReset] = useState(false); const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const notify = (message: string) => { setToast(message); clearTimeout(timer.current); timer.current = setTimeout(() => setToast(''), 5000); };
  useEffect(() => { setSidebar(false); }, [route]);
  useEffect(() => () => clearTimeout(timer.current), []);
  const workspace = resolveWorkspace(route, state.projects);
  const activePath = workspace ? `/assistants/${workspace.mode}` : route.split('?')[0];
  const projectArea = activePath === '/projects' || activePath.startsWith('/assistants/');
  const path = route.split('?')[0], searchQuery = new URLSearchParams(route.split('?')[1]).get('q') || '';
  let content;
  if (workspace) content = workspace.mode === 'writer' ? <WriterStudio key={workspace.projectId} projectId={workspace.projectId}/> : <DirectorStudio key={workspace.projectId} projectId={workspace.projectId}/>;
  else if (path === '/canvas') content = <CanvasDemo/>;
  else if (path.startsWith('/owner')) content = <Owner key={path} reviewId={path.split('/')[3]}/>;
  else if (path.startsWith('/ips/')) content = <IPDetail id={path.split('/')[2]}/>;
  else if (path === '/ips') content = <IPGallery key={searchQuery} initialQuery={searchQuery}/>;
  else if (path.startsWith('/tasks/')) content = <TaskDetail id={path.split('/')[2]}/>;
  else if (path === '/tasks') content = <Tasks/>;
  else if (path === '/projects') content = <Projects/>;
  else if (path === '/assistants/writer' || path === '/assistants/director') content = <Projects key={path} assistant={path.endsWith('/writer') ? 'writer' : 'director'}/>;
  else if (path === '/assets') content = <Assets/>;
  else if (path === '/works') content = <Works/>;
  else if (path === '/guide') content = <Guide/>;
  else content = <IPHome/>;
  return <NoticeContext.Provider value={notify}><div className="app-shell">
    {sidebar && <button className="sidebar-scrim" aria-label="收起导航" onClick={() => setSidebar(false)}/>}
    <aside className={`sidebar ${sidebar ? 'open' : ''}`}><a className="brand" href="#/" aria-label="imaideo 首页"><span className="brand-symbol"><i/><i/><i/></span>imaideo<span className="brand-dot">.</span></a><IconButton label="收起导航" onClick={() => setSidebar(false)}><PanelLeftClose size={18}/></IconButton>
      <Button className="new-project" onClick={() => nav('/projects')}><Plus size={18}/>开始创作</Button>
      <nav aria-label="主导航">{links.map(({ path: p, label, icon: Icon }) => p === '/projects' ? <div className="sidebar-project-group" key={p}><a href="#/projects" aria-current={activePath === '/projects' ? 'page' : undefined} className={projectArea ? 'active' : ''}><Icon size={19}/><span>{label}</span></a><div className="sidebar-subnav" aria-label="我的项目分区">{projectLinks.map(({ path: subPath, label: subLabel, icon: SubIcon }) => <a href={`#${subPath}`} key={subPath} aria-current={activePath === subPath ? 'page' : undefined} className={activePath === subPath ? 'active' : ''}><SubIcon size={16}/><span>{subLabel}</span></a>)}</div></div> : <a href={`#${p}`} key={p} aria-current={activePath === p || p !== '/' && activePath.startsWith(p) ? 'page' : undefined} className={activePath === p || p !== '/' && activePath.startsWith(p) ? 'active' : ''}><Icon size={19}/><span>{label}</span>{p === '/ips' && <span className="nav-label">探索</span>}</a>)}</nav>
      <div className="sidebar-bottom"><div className="partner-note"><span className="small-symbol"><Sparkles size={17}/></span><strong>让经典，生长出新故事</strong><p>好故事值得被再次看见。</p><button onClick={() => nav('/owner')}>成为共创伙伴<ArrowUpRight size={15}/></button></div><a className={path.startsWith('/owner') ? 'bottom-link active' : 'bottom-link'} href="#/owner"><BriefcaseBusiness size={18}/>版权方中心<ArrowUpRight size={14}/></a><a className="bottom-link" href="#/guide"><CircleHelp size={18}/>演示指南<span>5 min</span></a><button className="identity" onClick={() => { setRole(state.role === 'creator' ? 'owner' : 'creator'); notify(`已切换为演示${state.role === 'creator' ? '版权方' : '创作者'}`); }}><span className="avatar">{state.role === 'creator' ? '林' : '云'}</span><span><strong>{state.role === 'creator' ? '林间' : '云山故事社'}</strong><small>演示{state.role === 'creator' ? '创作者' : '版权方'}</small></span><RefreshCw size={15}/></button><button className="reset-link" onClick={() => setReset(true)}><RotateCcw size={12}/>重置演示<span>v1.0</span></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="topbar-spacer"><button className="mobile-menu icon-button" aria-label="打开导航" onClick={() => setSidebar(true)}><Menu size={20}/></button></div><button className="points-balance" onClick={() => notify('积分功能为演示数据，暂不支持充值')}><span>✦</span> 积分余额 <strong>1,280</strong></button><button className="login-demo" onClick={() => notify('演示环境：登录功能暂未接入')}>登录 / 注册</button></header>
      {getSaveError() && <div className="storage-warning" role="alert">{getSaveError()}</div>}
      <main className={workspace ? 'main-content studio-content' : 'main-content'} id="main-content">{content}</main><footer className="footer"><span>imaideo · 让经典拥有新故事</span><span>本地演示 / 预置创作内容 / 无真实交易</span></footer>
    </div>
    {toast && <div className="toast" role="status"><Info size={17}/>{toast}<button aria-label="关闭提示" onClick={() => setToast('')}><X size={16}/></button></div>}
    {reset && <Dialog title="重新开始这场共创" onClose={() => setReset(false)}><p>这会清除本浏览器中的演示修改、任务和投稿，并恢复初始示例。不会影响线上网站。</p><div className="dialog-actions"><Button variant="secondary" onClick={() => setReset(false)}>保留当前进度</Button><Button variant="danger" onClick={() => { resetDemo(); setReset(false); nav('/'); notify('已恢复初始演示数据'); }}>重置演示数据</Button></div></Dialog>}
  </div></NoticeContext.Provider>;
}
export function IPCard({ ip, compact = false }: { ip: IP; compact?: boolean }) { return <button className={`ip-card ${compact ? 'compact' : ''}`} onClick={() => nav(`/ips/${ip.id}`)}><div className="ip-image"><Artwork cover={ip.cover} title={ip.title}/><span className={`image-badge ${ip.available ? '' : 'muted-badge'}`}>{ip.available ? '原创示例 · 可体验' : '拟合作方向'}</span><span className="image-open"><ArrowUpRight size={19}/></span><div className="poster-title"><span>{ip.genre}</span><h3>{ip.title}</h3></div></div><div className="ip-card-copy"><p>{ip.subtitle}</p><span>{ip.available ? <><Layers3 size={13}/>示例资产包已就绪</> : <><LockKeyhole size={13}/>未获授权 · 暂未开放创作</>}</span></div></button>; }
export function TaskCard({ task }: { task: Commission }) { const { ips } = useDemo(); const ip = ips.find(i => i.id === task.ipId)!; return <button className="task-card" onClick={() => nav(`/tasks/${task.id}`)}><Artwork cover={ip.cover}/><div className="task-card-body"><div className="card-top"><span>{ip.title}</span><Tag tone={isClosed(task) ? '' : 'open'}>{isClosed(task) ? '已截止' : '征集中'}</Tag></div><h3>{task.title}</h3><p>{task.brief}</p><div className="task-meta"><span>{task.format} / {task.seconds} 秒</span><span><Clock3 size={13}/>{formatDate(task.deadline)} 截止</span></div><div className="task-reward"><strong>{task.reward}</strong><span>演示激励<ArrowUpRight size={16}/></span></div></div></button>; }
function IPShowcaseCard({ ip }: { ip: IP }) { return <button className="ip-showcase-card" onClick={() => nav(`/ips/${ip.id}`)}><div className="ip-showcase-art"><Artwork cover={ip.cover} title={ip.title}/><span className="ip-showcase-badge">{ip.demoOnly ? '演示 IP' : '原创示例'}</span><ArrowUpRight className="ip-showcase-arrow" size={17}/></div><div className="ip-showcase-copy"><span>{ip.category}</span><h3>{ip.title}</h3><p>{ip.subtitle}</p></div></button>; }
function IPRail({ title, items, count, onMore }: { title: string; items: IP[]; count?: number; onMore?: () => void }) { return <section className="ip-category-section"><div className="ip-category-header"><div><h2>{title}</h2><span>{count ?? items.length} 个世界</span></div>{onMore && <button className="text-link" onClick={onMore}>查看全部<ArrowRight size={15}/></button>}</div><div className="ip-rail"><div className="ip-rail-track">{items.map(ip => <IPShowcaseCard ip={ip} key={ip.id}/>)}</div></div></section>; }
function IPHome() {
  const { ips, tasks, projects } = useDemo(); const [query, setQuery] = useState(''); const [category, setCategory] = useState<'全部' | IP['category']>('全部'); const [preview, setPreview] = useState<Project | null>(null);
  const catalog = ips.filter(ip => ip.demoOnly).sort((a, b) => a.sortOrder - b.sortOrder); const originals = ips.filter(ip => !ip.demoOnly && ip.available); const filtered = catalog.filter(ip => (category === '全部' || ip.category === category) && `${ip.title} ${ip.subtitle} ${ip.description}`.includes(query.trim())); const categories: IP['category'][] = ['童年经典', '国漫动画', '游戏世界', '国际 IP']; const ongoing = projects.filter(p => p.status !== 'selected').slice(0, 3);
  return <><section className="home-hero-compact"><div className="home-hero-copy"><Tag>IP 资源演示库 · {catalog.length} 个世界</Tag><h1>一万个熟悉的世界，<br/><span>等你写下新的故事。</span></h1><p>从童年经典到游戏世界，选择一个 IP，开始你的下一部作品。</p><div className="home-hero-actions"><Button onClick={() => nav('/projects')}><Plus size={16}/>开始创作</Button><Button variant="secondary" onClick={() => nav('/ips')}>浏览全部 IP<ArrowRight size={16}/></Button></div></div><div className="home-hero-orbit"><span>熟悉</span><strong>IP</strong><span>新故事</span></div></section><section className="home-ip-toolbar"><div className="home-search"><Search size={18}/><input aria-label="搜索 IP" value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索你熟悉的 IP"/><kbd>⌘ K</kbd></div><div className="home-category-tabs" aria-label="IP 分类"><button className={category === '全部' ? 'active' : ''} onClick={() => setCategory('全部')}>全部</button>{categories.map(item => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div></section>{query || category !== '全部' ? <IPRail title={query ? `搜索结果 · ${filtered.length}` : category} items={filtered} count={filtered.length}/>: <><IPRail title="精选 IP" items={catalog.filter(ip => ip.featured)} count={catalog.filter(ip => ip.featured).length} onMore={() => nav('/ips')}/>{categories.map(item => <IPRail key={item} title={item} items={catalog.filter(ip => ip.category === item)} count={catalog.filter(ip => ip.category === item).length} onMore={() => { setCategory(item); window.scrollTo({ top: 250, behavior: 'smooth' }); }}/>)}</>} {!filtered.length && (query || category !== '全部') && <Empty title="暂时没有找到这个 IP" detail="换一个关键词试试，或浏览全部分类。" action="浏览全部 IP" onAction={() => { setQuery(''); setCategory('全部'); }}/>}<IPRail title="原创示例" items={originals} count={originals.length} onMore={() => nav('/ips')}/><section><SectionHead title="好故事，正在征集" detail="带着你的创意来，让作品成为下一次相遇。" action="全部征集" onAction={() => nav('/tasks')}/><div className="task-grid">{tasks.slice(0, 3).map(t => <TaskCard key={t.id} task={t}/>)}</div></section><section><SectionHead title="继续你的创作" action="我的项目" onAction={() => nav('/projects')}/><div className="continue-grid">{ongoing.map(p => <button className="continue-card" key={p.id} onClick={() => nav(`/studio/${p.id}`)}><Artwork cover={ips.find(i => i.id === p.ipId)!.cover} frame={2}/><div><Status status={p.status}/><h3>{p.title}</h3><span>{ips.find(i => i.id === p.ipId)!.title} · {p.shots.length} 个镜头</span></div><ArrowUpRight size={17}/></button>)}</div></section><section className="screening-banner"><Artwork cover="cloud" frame={5}/><div><Tag>作品展映 · 原创示例</Tag><h2>每一个新故事，<br/>都是一次重新相遇。</h2><Button variant="secondary" onClick={() => setPreview(projects.find(p => p.status === 'selected')!)}><Play size={15}/>观看分镜预演</Button></div></section>{preview && <Animatic project={preview} onClose={() => setPreview(null)}/>}</>;
}
export function Hall() {
  const { ips, tasks, projects } = useDemo(); const [preview, setPreview] = useState<Project | null>(null);
  const ongoing = projects.filter(p => p.status !== 'selected').slice(0, 3);
  return <><div className="welcome-row"><div><h1>好故事，从这里继续。</h1><p>发现值得新生的 IP，与经典一起，创造下一篇章。</p></div><a className="text-link" href="#/guide">第一次来？看看如何共创<ArrowUpRight size={15}/></a></div>
    <section className="hero"><Artwork cover="cloud"/><div className="hero-shade"/><div className="hero-copy"><Tag>经典 IP · 全新可能</Tag><h2>让熟悉的世界，<br/>长出新的故事。</h2><p>从一个 IP、一份资产、一场共创开始。<br/>把想象，变成下一部作品。</p><div className="hero-actions"><Button onClick={() => nav('/ips')}>探索 IP 世界<ArrowRight size={17}/></Button><Button variant="secondary" onClick={() => nav('/tasks')}>参与创作征集</Button></div><div className="hero-proof"><Layers3 size={14}/><span>IP 资产</span><span className="proof-divider"/><FileText size={14}/><span>故事创作</span><span className="proof-divider"/><Film size={14}/><span>作品共创</span></div></div><button className="hero-feature" onClick={() => nav('/ips/cloud')}><span>本期原创示例</span><strong>云山邮局<ArrowUpRight size={18}/></strong><small>一封信，穿过山海与时间。</small></button><div className="hero-pagination"><span className="active"/><span/><span/></div></section>
    <div className="quick-actions"><button onClick={() => nav('/tasks')}><span className="quick-icon"><Clapperboard size={21}/></span><span><strong>参与一场共创</strong><small>从版权方的创作命题开始</small></span><ArrowUpRight size={18}/></button><button onClick={() => nav('/projects')}><span className="quick-icon"><Sparkles size={21}/></span><span><strong>进入创作工作台</strong><small>剧本、资产、分镜，一路连贯</small></span><ArrowUpRight size={18}/></button><button onClick={() => nav('/owner')}><span className="quick-icon"><BriefcaseBusiness size={21}/></span><span><strong>我是版权方</strong><small>发布资产，让新故事发生</small></span><ArrowUpRight size={18}/></button></div>
    <section><SectionHead title="发现值得续写的世界" detail="从原创体验到经典合作构想，找到与你共鸣的故事。" action="全部 IP" onAction={() => nav('/ips')}/><div className="ip-grid home-ip-grid">{[ips[0], ips[1], ips[2], ips[4]].map(ip => <IPCard key={ip.id} ip={ip}/>)}</div></section>
    <section><SectionHead title="好故事，正在征集" detail="带着你的创意来，让作品成为下一次相遇。" action="全部征集" onAction={() => nav('/tasks')}/><div className="task-grid">{tasks.slice(0, 3).map(t => <TaskCard key={t.id} task={t}/>)}</div></section>
    <section><SectionHead title="继续你的创作" action="我的项目" onAction={() => nav('/projects')}/><div className="continue-grid">{ongoing.map(p => <button className="continue-card" key={p.id} onClick={() => nav(`/studio/${p.id}`)}><Artwork cover={ips.find(i => i.id === p.ipId)!.cover} frame={2}/><div><Status status={p.status}/><h3>{p.title}</h3><span>云山邮局 · {p.shots.length} 个镜头</span></div><ArrowUpRight size={17}/></button>)}</div></section>
    <section className="screening-banner"><Artwork cover="cloud" frame={5}/><div><Tag>作品展映 · 原创示例</Tag><h2>每一个新故事，<br/>都是一次重新相遇。</h2><Button variant="secondary" onClick={() => setPreview(projects.find(p => p.status === 'selected')!)}><Play size={15}/>观看分镜预演</Button></div></section>{preview && <Animatic project={preview} onClose={() => setPreview(null)}/>}</>;
}
function IPGallery({ initialQuery }: { initialQuery: string }) {
  const { ips } = useDemo(); const [query, setQuery] = useState(initialQuery), [category, setCategory] = useState('全部'), [availability, setAvailability] = useState('全部状态'), [format, setFormat] = useState('全部形式');
  const list = ips.filter(i => `${i.title} ${i.description}`.includes(query) && (category === '全部' || i.category === category) && (availability === '全部状态' || availability === '可体验示例' && i.available || availability === '演示资料' && i.demoOnly) && (format === '全部形式' || i.format === format));
  return <><PageHead title="发现你的下一个世界" detail="熟悉的记忆，全新的想象。让故事从一个 IP 开始。"/><div className="filter-bar"><div className="pill-tabs" aria-label="IP 分类">{['全部', '童年经典', '国漫动画', '游戏世界', '国际 IP'].map(x => <button key={x} className={category === x ? 'active' : ''} onClick={() => setCategory(x)}>{x}</button>)}</div><div className="filter-controls"><select aria-label="内容形式" value={format} onChange={e => setFormat(e.target.value)}><option>全部形式</option><option>动画短片</option><option>动态漫</option><option>互动故事</option></select><select aria-label="IP 开放状态" value={availability} onChange={e => setAvailability(e.target.value)}><option>全部状态</option><option>可体验示例</option><option>演示资料</option></select><div className="search-box"><Search size={16}/><input aria-label="搜索 IP 名称" value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索 IP 名称"/></div></div></div><div className="results-label">{list.length} 个故事世界<span>IP 资源演示库 · 本地示例数据</span></div>{list.length ? <div className="ip-grid">{list.map(i => <IPCard ip={i} key={i.id}/>)}</div> : <Empty title="还没有找到这个世界" detail="试试其他名称，或清除筛选重新探索。" action="清除筛选" onAction={() => { setQuery(''); setCategory('全部'); setAvailability('全部状态'); setFormat('全部形式'); }}/>}</>;
}
function IPDetail({ id }: { id: string }) {
  const { ips, assets, tasks } = useDemo(); const ip = ips.find(x => x.id === id); const [asset, setAsset] = useState<Asset | null>(null);
  if (!ip) return <Empty title="这个 IP 不在演示库中" detail="返回 IP 广场继续探索。" action="返回 IP 广场" onAction={() => nav('/ips')}/>;
  const ipAssets = assets.filter(a => a.ipId === id && a.source === 'ip');
  return <><PageHead title={ip.title} detail={ip.subtitle} back="/ips"><Tag tone={ip.available ? 'open' : ''}>{ip.available ? '原创示例 · 可体验' : 'IP 资源演示资料'}</Tag></PageHead><div className="ip-detail-hero"><Artwork cover={ip.cover}/><div className="detail-overlay"><span>{ip.category} / {ip.format}</span><h2>{ip.subtitle}</h2><p>{ip.description}</p>{ip.available ? <Button onClick={() => nav(`/tasks/${tasks.find(t => t.ipId === id)?.id}`)}>参与这个世界的创作<ArrowRight size={16}/></Button> : <Button variant="secondary" onClick={() => document.getElementById('ip-demo-material')?.scrollIntoView({ behavior: 'smooth' })}>查看演示资料<ArrowRight size={16}/></Button>}</div></div><div className="detail-columns" id="ip-demo-material"><div><SectionHead title="关于这个世界"/><p className="reading-copy">{ip.world}</p><SectionHead title={ip.available ? '创作资产包' : '可延展的创作方向'} detail={ip.available ? '先认识角色与场景，再开始你的故事。全部为演示原创素材。' : '当前提供世界观预览，完整资产包将在后续试点中接入。'}/>{ip.available ? <div className="asset-grid">{ipAssets.map(a => <AssetCard asset={a} onClick={() => setAsset(a)} key={a.id}/>)}</div> : <div className="notice-block"><Sparkles size={20}/><p>角色支线、世界观补完、短片改编与互动故事都可以成为这个 IP 的新创作方向。</p></div>}</div><aside className="detail-aside"><h3><ShieldCheck size={18}/>演示资料</h3><p>{ip.rules}</p><div className="divider"/><small>资料状态</small><strong>{ipAssets.length} 份可用资产</strong><small>{ip.available ? '原创示例，可进入完整创作流程。' : '当前可浏览资料，不创建项目。'}</small></aside></div>{ip.available && <section><SectionHead title="来自这个世界的创作邀请"/><div className="task-grid">{tasks.filter(t => t.ipId === id).map(t => <TaskCard task={t} key={t.id}/>)}</div></section>}{asset && <AssetDialog asset={asset} onClose={() => setAsset(null)}/>}</>;
}
function Tasks() {
  const { tasks, ips } = useDemo(); const [q, setQ] = useState(''), [state, setState] = useState('全部'), [ip, setIP] = useState('全部 IP');
  const list = tasks.filter(t => t.title.includes(q) && (ip === '全部 IP' || t.ipId === ip) && (state === '全部' || isClosed(t) === (state === '已截止')));
  return <><PageHead title="让你的创意，被看见" detail="参与公开征集，使用示例资产完成创作，与版权方一起打磨新故事。"/><div className="filter-bar"><div className="pill-tabs">{['全部', '征集中', '已截止'].map(x => <button key={x} className={state === x ? 'active' : ''} onClick={() => setState(x)}>{x}</button>)}</div><div className="filter-controls"><select aria-label="按 IP 筛选任务" value={ip} onChange={e => setIP(e.target.value)}><option>全部 IP</option>{ips.filter(i => i.available).map(i => <option value={i.id} key={i.id}>{i.title}</option>)}</select><div className="search-box"><Search size={16}/><input aria-label="搜索任务" placeholder="搜索征集任务" value={q} onChange={e => setQ(e.target.value)}/></div></div></div><div className="results-label">{list.length} 项创作邀请<span>征集规则与激励金额均为演示示例</span></div>{list.length ? <div className="task-grid">{list.map(t => <TaskCard task={t} key={t.id}/>)}</div> : <Empty title="暂时没有符合条件的征集" detail="调整筛选，或切换到版权方中心发布一项演示任务。"/>}</>;
}
function TaskDetail({ id }: { id: string }) {
  const { tasks, ips, assets, role } = useDemo(); const task = tasks.find(t => t.id === id); const notify = useNotice(); const [ack, setAck] = useState(false);
  if (!task) return <Empty title="任务不存在" detail="请返回任务广场。" action="返回任务广场" onAction={() => nav('/tasks')}/>;
  const ip = ips.find(i => i.id === task.ipId)!;
  function join() { try { nav(`/studio/${joinTask(id)}`); } catch (e) { notify((e as Error).message); } }
  return <><PageHead title={task.title} detail={`${ip.title} · 公开征集成片`} back="/tasks"><Tag tone="open">{isClosed(task) ? '已截止' : '正在征集'}</Tag></PageHead><div className="task-detail-grid"><div><Artwork cover={ip.cover} className="task-detail-art"/><SectionHead title="这一次，想邀请你讲这样的故事"/><p className="reading-copy">{task.brief}</p><div className="task-requirements"><div><Film size={20}/><small>作品形式</small><strong>{task.format}</strong></div><div><Clock3 size={20}/><small>成片时长</small><strong>{task.seconds} 秒</strong></div><div><Users size={20}/><small>征集方式</small><strong>公开成片投稿</strong></div></div><SectionHead title="你将获得的创作资产"/><div className="asset-list">{assets.filter(a => task.assetIds.includes(a.id)).map(a => <div key={a.id}><Layers3 size={16}/><span>{a.name}</span><small>{a.kind} / v{a.version}</small></div>)}</div><SectionHead title="评选与反馈"/><p className="reading-copy">{task.criteria}。版权方可按镜头提出修改意见，创作者修改后提交新版本，原投稿保留。</p></div><aside className="task-join"><Tag>演示征集</Tag><h2>{task.reward}</h2><p>示例激励，不涉及真实支付。</p><dl><dt>投稿截止</dt><dd>{task.deadline}</dd><dt>提供方</dt><dd>{ip.owner}</dd><dt>提交内容</dt><dd>分镜预演、剧本与创作说明</dd></dl><h3>开始前，请了解创作边界</h3><p>{task.rules}</p><label className="checkbox-label"><input type="checkbox" checked={ack} onChange={e => setAck(e.target.checked)}/>我已阅读演示创作规则，了解全部素材为示例内容。</label>{role !== 'creator' ? <Button onClick={() => { setRole('creator'); notify('已切换为演示创作者'); }}>切换创作者身份</Button> : <Button disabled={!ack || isClosed(task)} onClick={join}>{isClosed(task) ? '征集已截止' : '加入征集并开始创作'}<ArrowRight size={16}/></Button>}<small>加入后即可使用本任务开放的示例资产。</small></aside></div></>;
}
function Projects({ assistant }: { assistant?: 'writer' | 'director' }) {
  const state = useDemo(), { projects, ips } = state;
  const notify = useNotice();
  const [status, setStatus] = useState('all'), [q, setQ] = useState('');
  const labels = [['all', '全部项目'], ['draft', '草稿'], ['producing', '制作中'], ['review', '待审核'], ['changes', '需修改'], ['selected', '已入选']];
  const list = projects.filter(p => (status === 'all' || p.status === status) && p.title.includes(q) && (!assistant || ips.some(ip => ip.id === p.ipId && ip.available && !ip.demoOnly)));
  const assistantName = assistant === 'writer' ? '编剧助手' : '导演助手';
  const startStory = () => { try { nav(assistantPath(createAssistantProject(), assistant ?? 'writer')); } catch (e) { notify((e as Error).message); } };
  return <>
    <PageHead title={assistant ? assistantName : '我的项目'} detail={assistant ? `选择一个项目，进入${assistantName}。${assistant === 'writer' ? '策划、人物、大纲、剧本与连续性记录。' : '资产确认、分镜设计、提示词与制作检查。'}内容随项目自动保存。` : '选择编剧助手或导演助手，继续你的项目。'}>
      <Button onClick={startStory}><Plus size={16}/>开始新故事</Button>
    </PageHead>
    {!assistant && <div className="project-workspaces" aria-label="我的项目创作板块">
      <a href="#/assistants/writer"><FileText size={22}/><span><strong>编剧助手</strong><small>策划故事、编辑剧本、确认版本</small></span><ArrowRight size={17}/></a>
      <a href="#/assistants/director"><Film size={22}/><span><strong>导演助手</strong><small>管理资产、设计分镜、制作投稿</small></span><ArrowRight size={17}/></a>
    </div>}
    <div className="filter-bar"><div className="pill-tabs">{labels.map(([v, l]) => <button className={status === v ? 'active' : ''} onClick={() => setStatus(v)} key={v}>{l}</button>)}</div><div className="search-box"><Search size={16}/><input aria-label="搜索项目" placeholder="搜索项目" value={q} onChange={e => setQ(e.target.value)}/></div></div>
    {list.length ? <div className="project-grid">{list.map(p => <article className="project-card" key={p.id}>
      <button className="project-card-open" aria-label={`${assistant ? `进入${assistantName}` : '打开项目'}：${p.title}`} onClick={() => nav(assistant ? assistantPath(p.id, assistant) : `/studio/${p.id}`)}>
        <div className="project-picture"><Artwork cover={ips.find(i => i.id === p.ipId)!.cover} frame={p.ipId === 'cloud' ? projects.indexOf(p) % 6 : undefined}/><Status status={p.status}/><span className="project-enter"><ArrowUpRight size={20}/></span></div>
        <div className="project-card-copy"><h3>{p.title}</h3><p>{ips.find(i => i.id === p.ipId)!.title} · {p.shots.length} 个镜头</p>
          {assistant ? <p className="project-stage">{assistant === 'writer' ? scriptCurrent(p) ? '剧本已确认 · 可交接' : '编剧资料待确认' : !scriptCurrent(p) ? '等待编剧确认 / 更新' : !assetsCurrent(p, state) ? '资产待确认' : !storyboardCurrent(p, state) ? '分镜待核对' : !promptsCurrent(p, state) ? '提示词待更新' : '制作资料已就绪'}</p> : <div className="project-progress"><span style={{ width: `${p.shots.filter(s => s.selected).length / p.shots.length * 100}%` }}/></div>}
          <div className="project-meta"><span>{assistant === 'writer' ? `确认版本：${p.assistant?.versions.length ?? 0} 个` : `${p.shots.filter(s => s.selected).length}/${p.shots.length} 镜头就绪`}</span><span>{formatDate(p.updatedAt)} 更新</span></div>
        </div>
      </button>
      {ips.some(ip => ip.id === p.ipId && ip.available && !ip.demoOnly) && <div className="project-assistant-actions"><a href={`#${assistantPath(p.id, 'writer')}`}><FileText size={14}/>编剧助手</a><a href={`#${assistantPath(p.id, 'director')}`}><Film size={14}/>导演助手</a></div>}
    </article>)}</div> : <Empty title="这里还没有故事" detail="创建一个空白故事，进入对应的创作工作流。" action="开始新故事" onAction={startStory}/>}
  </>;
}
export function AssetCard({ asset, onClick }: { asset: Asset; onClick: () => void }) { return <button className="asset-card" onClick={onClick}><Artwork cover={asset.cover} frame={asset.frame}/><div><Tag>{asset.kind}</Tag><h3>{asset.name}</h3><span>{asset.source === 'ip' ? 'IP 示例官方素材' : '个人参考素材'} · v{asset.version}</span></div></button>; }
export function AssetDialog({ asset, onClose }: { asset: Asset; onClose: () => void }) { const notice = useNotice(); return <Dialog title={asset.name} onClose={onClose}><Artwork cover={asset.cover} frame={asset.frame} className="asset-preview"/><div className="asset-detail-tags"><Tag>{asset.kind}</Tag><Tag>v{asset.version}</Tag><Tag>演示原创素材</Tag></div><p>{asset.description}</p><p className="muted">来源：{asset.source === 'ip' ? '原创示例 IP 资产包' : '演示创作者个人资料'}。仅用于本样板创作体验。</p><Button variant="secondary" onClick={() => { const data = JSON.stringify(asset, null, 2); const url = URL.createObjectURL(new Blob([data], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `${asset.name}-资产说明.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 500); notice('已导出资产说明'); }}><Download size={16}/>导出资产说明</Button></Dialog>; }
function Assets() {
  const { assets, ips, projects } = useDemo(); const [tab, setTab] = useState('ip'), [kind, setKind] = useState('全部类型'), [ip, setIP] = useState('全部 IP'), [selected, setSelected] = useState<Asset | null>(null), [personal, setPersonal] = useState(false); const notice = useNotice();
  const list = assets.filter(a => (tab === 'project' ? projects.some(p => p.assetIds.includes(a.id)) : a.source === tab) && (kind === '全部类型' || a.kind === kind) && (ip === '全部 IP' || a.ipId === ip));
  function add(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); const name = String(f.get('name')).trim(), description = String(f.get('description')).trim(); if (!name || !description) return; update(d => d.assets.push({ id: crypto.randomUUID(), ipId: String(f.get('ip')), name, description, kind: f.get('kind') as Asset['kind'], version: '1.0', source: 'personal', cover: String(f.get('ip')) })); setPersonal(false); setTab('personal'); notice('个人参考说明已保存在本机'); }
  return <><PageHead title="每个世界，都有迹可循" detail="让角色、场景与道具成为可靠的创作基础。来源与版本，始终清晰可见。"><Button variant="secondary" onClick={() => setPersonal(true)}><Plus size={16}/>添加个人参考</Button></PageHead><div className="filter-bar"><div className="pill-tabs">{[['ip', 'IP 官方素材'], ['project', '项目使用素材'], ['personal', '个人素材']].map(([v, l]) => <button key={v} className={tab === v ? 'active' : ''} onClick={() => setTab(v)}>{l}</button>)}</div><div className="filter-controls"><select aria-label="资产类型" value={kind} onChange={e => setKind(e.target.value)}>{['全部类型', '角色', '场景', '道具'].map(k => <option key={k}>{k}</option>)}</select><select aria-label="资产所属 IP" value={ip} onChange={e => setIP(e.target.value)}><option>全部 IP</option>{ips.filter(i => i.available).map(i => <option key={i.id} value={i.id}>{i.title}</option>)}</select></div></div>{list.length ? <div className="asset-grid library-grid">{list.map(a => <AssetCard key={a.id} asset={a} onClick={() => setSelected(a)}/>)}</div> : <Empty title="还没有这类素材" detail="切换筛选，或添加一份个人参考说明。"/>}{selected && <AssetDialog asset={selected} onClose={() => setSelected(null)}/>} {personal && <Dialog title="添加个人参考说明" onClose={() => setPersonal(false)}><p className="muted">首版记录素材说明与示例封面，不上传私人文件。</p><form onSubmit={add}><Field label="名称"><input name="name" required maxLength={60}/></Field><div className="form-grid"><Field label="所属示例 IP"><select name="ip">{ips.filter(i => i.available).map(i => <option key={i.id} value={i.id}>{i.title}</option>)}</select></Field><Field label="类型"><select name="kind"><option>场景</option><option>角色</option><option>道具</option></select></Field></div><Field label="参考说明"><textarea name="description" required rows={4}/></Field><Button type="submit">保存个人参考</Button></form></Dialog>}</>;
}
function Works() { const { submissions, ips } = useDemo(); const [preview, setPreview] = useState<Project | null>(null); const works = submissions.filter(s => s.status === 'selected'); return <><PageHead title="熟悉的世界，新的回响" detail="看看创作者如何让想象落地。以下均为演示入选作品与分镜预演。"/>{works.length ? <div className="works-grid">{works.map(s => <article className="work-card" key={s.id}><button className="work-play" onClick={() => setPreview(s.snapshot)}><Artwork cover={ips.find(i => i.id === s.snapshot.ipId)!.cover} frame={s.snapshot.ipId === 'cloud' ? 5 : undefined}/><span><Play size={24} fill="currentColor"/></span><Tag>分镜预演 · 演示</Tag></button><div className="work-description"><h2>{s.snapshot.submission.title}</h2><p>{s.snapshot.submission.summary}</p><div><span>{s.snapshot.submission.author}</span><button className="text-link" onClick={() => nav(`/ips/${s.snapshot.ipId}`)}>{ips.find(i => i.id === s.snapshot.ipId)!.title}<ArrowUpRight size={15}/></button></div><button className="text-link" onClick={() => nav(`/studio/${s.projectId}`)}>查看制作过程<ArrowRight size={15}/></button><button className="text-link" onClick={() => nav(`/tasks/${s.taskId}`)}>查看所属征集<ArrowUpRight size={15}/></button></div></article>)}</div> : <Empty title="新故事即将亮相" detail="在版权方中心将一份投稿设为入选，作品就会出现在这里。"/>}{preview && <Animatic project={preview} onClose={() => setPreview(null)}/>}</>; }
function Guide() { const { projects } = useDemo(); return <><PageHead title="五分钟，走完一次共创" detail="用一份示例任务，体验创作者与版权方如何共同完成一个故事。"/><div className="guide-layout"><div className="guide-steps">{[
  ['发现一个世界', '在 IP 广场浏览云山邮局，查看世界观、角色素材和允许的创作范围。', '探索 IP', '/ips/cloud'],
  ['参与一项征集', '打开“一封迟到的信”，阅读规则并加入征集，自动创建你的项目。', '参与任务', '/tasks/letters'],
  ['完成一次制作', '进入编剧助手，编辑并确认剧本后点击“交给导演助手”。在导演区确认资产、核对分镜、准备提示词和检查，再预演投稿。画布创作是独立展示页，不参与项目制作。', '进入示例项目', `/studio/${projects[0].id}`],
  ['让作品变得更好', '切换为版权方，打开投稿，添加镜头意见并退回；再切回创作者修改、生成并再次投稿。', '查看版权方中心', '/owner'],
  ['让新故事被看见', '版权方把修改后的作品设为入选，打开作品展映，查看提交时的独立版本。', '观看作品展映', '/works'],
].map(([title, body, action, path], i) => <div key={title}><span className="guide-number">0{i + 1}</span><div><h2>{title}</h2><p>{body}</p><Button variant="secondary" onClick={() => nav(path)}>{action}<ArrowRight size={15}/></Button></div></div>)}</div><aside className="detail-aside"><h3><Info size={18}/>关于这个演示</h3><p>所有角色均为本地演示身份。AI 内容与生成结果为预置样本，不会调用模型或产生费用。</p><p>数据仅保存在当前浏览器中，不会跨设备同步。侧栏底部可重置体验。</p><p>天书奇谭、九色鹿、雪孩子仅为拟合作方向，未获授权，不能进入创作流程。</p><div className="divider"/><h3>能力参考</h3><a href="https://github.com/lixiaoxiao9888-create/short-drama-factory" target="_blank" rel="noreferrer">Short-Drama Factory<ArrowUpRight size={14}/></a><a href="https://github.com/lixiaoxiao9888-create/manju-laoli-skill" target="_blank" rel="noreferrer">漫剧老李<ArrowUpRight size={14}/></a><p>工作台已融入编剧与导演的演示流程，可保存版本、检查交接并导出资料。结果为预置示例，不执行仓库脚本；后续真实接入需要文本、图像、视频服务及后端。</p></aside></div></>; }
