import { useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUp, ArrowDown, Check, CheckCircle2, Download, FileText, Film, Layers3, LoaderCircle, LockKeyhole, Play, RefreshCw, Send, Sparkles, XCircle } from 'lucide-react';
import { Animatic, Artwork, Button, Empty, Field, IconButton, Status, Tag, downloadJson, nav, useDemo, useNotice } from './ui';
import { changeProject, editShot, generateShot, sendSubmission, submissionProblem } from './service';
import AssistantPanel from './AssistantPanel';
import SeedancePanel from './SeedancePanel';
import type { Project, Shot } from './types';

const steps = ['故事与剧本', '角色与资产', '分镜设计', '视频制作', '作品投稿'];
export default function DirectorStudio({ projectId }: { projectId: string }) {
  const state = useDemo(), p = state.projects.find(p => p.id === projectId); const notify = useNotice();
  const [step, setStep] = useState(p?.status === 'review' || p?.status === 'selected' ? 4 : 1), [preview, setPreview] = useState(false);
  if (!p) return <Empty title="找不到这个项目" detail="项目资料可能已重置，请返回项目列表。" action="我的项目" onAction={() => nav('/projects')}/>;
  const ip = state.ips.find(i => i.id === p.ipId)!, task = state.tasks.find(t => t.id === p.taskId)!;
  const readOnly = state.role !== 'creator' || p.status === 'review' || p.status === 'selected';
  const ready = p.shots.filter(s => s.clipStatus === 'done' && s.selected).length;
  const submissions = state.submissions.filter(s => s.projectId === p.id).sort((a, b) => b.version - a.version);
  const attempt = (f: () => void) => { try { f(); } catch (e) { notify((e as Error).message); } };
  const renderSteps = <div className="studio-steps">{steps.map((label, i) => i > 0 && <button key={label} className={step === i ? 'active' : ''} onClick={() => setStep(i)}><span>{i < step ? <Check size={13}/> : i}</span>{label}</button>)}</div>;
  return <><div className="studio-heading"><div><button className="text-link" onClick={() => nav('/assistants/director')}><ArrowLeft size={14}/>导演助手</button><div className="studio-title"><h1>{p.title}</h1><Status status={p.status}/></div><p><button onClick={() => nav(`/ips/${ip.id}`)}>{ip.title}</button><span>/</span><button onClick={() => nav(`/tasks/${task.id}`)}>{task.title}</button><span>·</span><span>本机自动保存</span></p></div><div className="head-actions"><Button variant="secondary" onClick={() => downloadJson(p.title, { ...p, exportInfo: { mode: '人工编辑内容与制作快照' } })}><Download size={15}/>导出项目</Button><Button variant="secondary" onClick={() => setPreview(true)}><Play size={15}/>分镜预演</Button></div></div>
    {readOnly && <div className="notice-block compact"><LockKeyhole size={17}/><p>{state.role !== 'creator' ? '当前为版权方查看模式。切换为创作者身份后可编辑。' : p.status === 'review' ? '本次投稿正在审核，等待反馈后可继续修改。' : '作品已入选，当前项目只读。可参与其他任务开启新故事。'}</p></div>}
    {renderSteps}<div className="studio-body"><div className="studio-main"><AssistantPanel project={p} step={step} readOnly={readOnly} onStep={value => setStep(Math.max(1, Math.min(4, value)))}/><fieldset disabled={readOnly}>
      {step === 1 && <><div className="editor-section-head"><div><h2>让每个角色，始终如一。</h2><p>绑定 IP 资产，保留原作设定与版本。</p></div><Tag>{p.assetIds.length} 份已选</Tag></div><div className="studio-assets">{state.assets.filter(a => task.assetIds.includes(a.id) || a.source === 'personal' && a.ipId === p.ipId).map(a => <label className={`select-asset ${p.assetIds.includes(a.id) ? 'selected' : ''}`} key={a.id}><Artwork cover={a.cover} frame={a.frame}/><div><span><Tag>{a.kind}</Tag><small>v{a.version}</small></span><h3>{a.name}</h3><p>{a.description}</p></div><input aria-label={`选用${a.name}`} type="checkbox" checked={p.assetIds.includes(a.id)} onChange={e => changeProject(p.id, p => { if (e.target.checked) p.assetIds.push(a.id); else { p.assetIds = p.assetIds.filter(id => id !== a.id); p.shots.forEach(s => { if (s.assetIds.includes(a.id)) { s.assetIds = s.assetIds.filter(id => id !== a.id); s.clipStatus = 'idle'; s.selected = false; } }); } })}/></label>)}</div><Field label="本项目创作补充" hint="原作规则保持固定，补充内容仅用于本项目。"><textarea rows={4} value={p.assetNotes} onChange={e => changeProject(p.id, p => { p.assetNotes = e.target.value; })} placeholder="例如：晨景采用青灰色，信送达时逐渐转为暖色。"/></Field></>}
      {step === 2 && <><div className="editor-section-head"><div><h2>把故事，变成镜头。</h2><p>导演助手 · 参考漫剧老李的资产与分镜工作流</p></div><Tag>{p.shots.reduce((n, s) => n + s.duration, 0)} / {task.seconds} 秒</Tag></div>{p.script.body !== p.script.confirmedBody && <div className="notice-block compact"><InfoInline/>当前剧本尚未确认。现有分镜会保留，请前往编剧助手确认后继续制作。</div>}<div className="shot-editor-list">{p.shots.map((s, i) => <div className="shot-editor" key={s.id}><div className="shot-editor-top"><div><span className="shot-index">{String(i + 1).padStart(2, '0')}</span><h3>{s.title}</h3></div><div><IconButton label={`上移镜头${i + 1}`} disabled={i === 0 || readOnly} onClick={() => changeProject(p.id, p => { [p.shots[i - 1], p.shots[i]] = [p.shots[i], p.shots[i - 1]]; })}><ArrowUp size={15}/></IconButton><IconButton label={`下移镜头${i + 1}`} disabled={i === p.shots.length - 1 || readOnly} onClick={() => changeProject(p.id, p => { [p.shots[i + 1], p.shots[i]] = [p.shots[i], p.shots[i + 1]]; })}><ArrowDown size={15}/></IconButton></div></div><div className="shot-editor-content"><Artwork cover={ip.cover} frame={p.ipId === 'cloud' ? s.frame : undefined}/><ShotFields shot={s} project={p}/></div></div>)}</div></>}
      {step === 3 && <><div className="editor-section-head"><div><h2>让想象，逐帧发生。</h2><p>管理生成队列与镜头结果，并用于分镜预演。</p></div><Button onClick={() => attempt(() => { if (p.script.body !== p.script.confirmedBody) throw new Error('请先到编剧助手确认当前剧本。'); p.shots.filter(s => s.clipStatus !== 'done').forEach(s => generateShot(p.id, s.id)); })}><Sparkles size={15}/>生成全部</Button></div><div className="generation-grid">{p.shots.map((s, i) => <article className="generation-card" key={s.id}><div className="generation-picture"><Artwork cover={ip.cover} frame={p.ipId === 'cloud' ? s.frame : undefined}/><span className="image-badge">镜头 {String(i + 1).padStart(2, '0')} · {s.duration}s</span>{['queued', 'running'].includes(s.clipStatus) && <div className="generation-overlay"><LoaderCircle className="spin" size={25}/><strong>{s.clipStatus === 'queued' ? '排队中…' : '生成中…'}</strong></div>}{s.clipStatus === 'failed' && <div className="generation-overlay failed"><XCircle size={25}/><strong>生成失败</strong><small>请重新生成</small></div>}</div><div className="generation-copy"><h3>{s.title}</h3><p>{s.camera} · {s.clipStatus === 'done' ? '结果已就绪' : s.clipStatus === 'idle' ? '等待生成' : s.clipStatus === 'failed' ? '可以重新生成' : '生成队列'}</p>{s.clipStatus === 'done' ? <label className="checkbox-label"><input type="checkbox" checked={s.selected} onChange={e => changeProject(p.id, p => { p.shots.find(x => x.id === s.id)!.selected = e.target.checked; })}/>选用此镜头结果</label> : <Button variant="secondary" disabled={['queued', 'running'].includes(s.clipStatus)} onClick={() => attempt(() => generateShot(p.id, s.id))}>{s.clipStatus === 'failed' ? <RefreshCw size={14}/> : <Sparkles size={14}/>}{s.clipStatus === 'failed' ? '重新生成' : '生成'}</Button>}</div></article>)}</div></>}
      {step === 4 && <><div className="editor-section-head"><div><h2>让故事，走向新的观众。</h2><p>提交会保存完整版本快照，版权方将审阅这一版本。</p></div><Tag>{submissions.length ? `已有 ${submissions.length} 个投稿版本` : '首次投稿'}</Tag></div><div className="submission-checks"><span className={ready === p.shots.length ? 'good' : ''}><CheckCircle2 size={16}/>{ready}/{p.shots.length} 镜头结果已选用</span><span className={p.script.body === p.script.confirmedBody ? 'good' : ''}><FileText size={16}/>{p.script.body === p.script.confirmedBody ? '剧本已确认' : '剧本待确认'}</span></div>{(['title', 'summary', 'author', 'note'] as const).map((field, i) => <Field key={field} label={['作品标题', '作品简介', '创作者署名', '创作说明'][i]}>{i === 0 || i === 2 ? <input value={p.submission[field]} onChange={e => changeProject(p.id, p => { p.submission[field] = e.target.value; if (field === 'title') p.title = e.target.value; })} maxLength={100}/> : <textarea rows={3} value={p.submission[field]} onChange={e => changeProject(p.id, p => { p.submission[field] = e.target.value; })}/>}</Field>)}{submissionProblem(state, p) && <p className="validation-message">{submissionProblem(state, p)}</p>}<Button disabled={Boolean(submissionProblem(state, p))} onClick={() => attempt(() => { sendSubmission(p.id); notify('投稿已保存，切换版权方可进行审核。'); })}><Send size={16}/>提交作品版本</Button></>}
    </fieldset>{step === 3 && <SeedancePanel projectId={p.id} readOnly={readOnly}/>} 
    {step === 4 && submissions.length > 0 && <section className="version-history"><h3>投稿与版权方反馈</h3>{submissions.map(s => <div className="version-row" key={s.id}><div><strong>投稿 v{s.version}</strong><Tag tone={s.status === 'selected' ? 'selected' : s.status === 'changes' ? 'changes' : 'review'}>{s.status === 'pending' ? '审核中' : s.status === 'changes' ? '待修改' : '已入选'}</Tag><small>{new Date(s.submittedAt).toLocaleString('zh-CN')}</small></div>{s.notes.map(n => <p key={n.id}><strong>{n.shotId ? s.snapshot.shots.find(x => x.id === n.shotId)?.title : '整体作品'}：</strong>{n.text}</p>)}<Button variant="ghost" onClick={() => nav(`/owner/review/${s.id}`)}>查看投稿快照<ArrowRight size={14}/></Button></div>)}</section>}
    </div><aside className="studio-aside"><div><h3><Layers3 size={17}/>创作依据</h3><strong>{ip.title}</strong><p>{ip.rules}</p><button className="text-link" onClick={() => nav(`/ips/${ip.id}`)}>查看 IP 资料<ArrowUpIcon/></button></div><div><h3><Film size={17}/>制作进度</h3><strong className="progress-number">{ready}<span> / {p.shots.length}</span></strong><p>镜头结果已选用</p><div className="project-progress"><span style={{ width: `${ready / p.shots.length * 100}%` }}/></div><Button variant="secondary" onClick={() => setPreview(true)}><Play size={14}/>播放分镜预演</Button></div></aside></div><div className="studio-step-footer"><Button variant="ghost" disabled={step === 1} onClick={() => setStep(step - 1)}><ArrowLeft size={15}/>上一步</Button><span>第 {step} / 4 步</span>{step < 4 ? <Button onClick={() => setStep(step + 1)}>下一步：{steps[step + 1]}<ArrowRight size={15}/></Button> : <Button variant="secondary" onClick={() => nav('/projects')}>返回我的项目</Button>}</div>{preview && <Animatic project={p} onClose={() => setPreview(false)}/>}</>;
}
function InfoInline() { return <LockKeyhole size={16}/>; }
function ArrowUpIcon() { return <ArrowRight size={14}/>; }
function ShotFields({ shot: s, project: p }: { shot: Shot; project: Project }) {
  const { assets } = useDemo();
  const edit = (patch: Partial<Shot>) => editShot(p.id, s.id, patch);
  return <div className="shot-fields"><Field label="镜头名称"><input value={s.title} maxLength={60} onChange={e => edit({ title: e.target.value })}/></Field><Field label="画面描述"><textarea rows={2} value={s.description} onChange={e => edit({ description: e.target.value })}/></Field><Field label="对白 / 旁白"><input value={s.dialogue} onChange={e => edit({ dialogue: e.target.value })} placeholder="可留空，保留环境声"/></Field><div className="form-grid"><Field label="时长（秒）"><input type="number" min={1} max={120} value={s.duration} onChange={e => edit({ duration: Math.max(1, Math.min(120, Number(e.target.value) || 1)) })}/></Field><Field label="运镜"><select value={s.camera} onChange={e => edit({ camera: e.target.value })}>{['缓慢推进', '中景转近景', '侧向跟拍', '手部特写', '固定中景', '缓缓拉远'].map(x => <option key={x}>{x}</option>)}</select></Field></div><div className="form-grid"><Field label="景别"><select value={s.framing || '中景'} onChange={e => edit({ framing: e.target.value })}>{['远景','全景','中景','近景','特写'].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="对白语气"><input value={s.tone || ''} onChange={e => edit({ tone: e.target.value })}/></Field></div><Field label="角色动作"><textarea rows={2} value={s.action || ''} onChange={e => edit({ action: e.target.value })}/></Field><Field label="声音"><input value={s.sound || ''} onChange={e => edit({ sound: e.target.value })}/></Field><Field label="接续状态"><textarea rows={2} value={s.continuity || ''} onChange={e => edit({ continuity: e.target.value })}/></Field><div className="shot-assets-label">引用资产</div><div className="asset-chips">{assets.filter(a => p.assetIds.includes(a.id)).map(a => <label key={a.id}><input type="checkbox" checked={s.assetIds.includes(a.id)} onChange={e => edit({ assetIds: e.target.checked ? [...s.assetIds, a.id] : s.assetIds.filter(x => x !== a.id) })}/>{a.name.split(' · ')[0]}</label>)}</div></div>;
}
